# Generated by Django 2.0.4 on 2018-04-24 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_advertisement_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.FloatField(default=0.0)),
                ('comment', models.CharField(max_length=200)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Advertisement')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='counter_offer',
            name='ad_id',
        ),
        migrations.RemoveField(
            model_name='counter_offer',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Counter_offer',
        ),
    ]
