# Generated by Django 2.0.4 on 2018-04-29 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180429_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counteroffer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Profile'),
        ),
    ]
