# Generated by Django 2.0.4 on 2018-04-29 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180429_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counteroffer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='ad_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Advertisement'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_buyer', to='app.Profile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_seller', to='app.Profile'),
        ),
    ]
